policycoreutils/sepolicy: fix stripsort for python 3
There's always None value in a list therefore stripsort() needs to know
how to work with it.

Fixes:
  File "/usr/lib64/python3.4/site-packages/sepolicy/gui.py", line 1439, in stripsort
    return (val1 > val2) - (val1 < val2)
TypeError: unorderable types: str() > NoneType()

Signed-off-by: Petr Lautrbach <plautrba@redhat.com>