sepolicy: Fix detection of writeable locations
- update substitutions from /etc/dnf/var

It seems that by default dnf api does not read /etc/dnf/var/* files to
update substitutions and so it can't resolve correct mirror list when a
variable is part of the link.

- alway run query.run()

Fixes:
    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/dnf/repo.py", line 574, in load
        ret = self._repo.load()
              ^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.12/site-packages/libdnf/repo.py", line 467, in load
        return _repo.Repo_load(self)
               ^^^^^^^^^^^^^^^^^^^^^
    libdnf._error.Error: Failed to download metadata for repo 'baseos':
    Cannot prepare internal mirrorlist: Status code: 404 for
    https://mirrors.centos.org/metalink?repo=centos-baseos-$stream&arch=x86_64&protocol=https,http (IP:152.19.134.198)

Signed-off-by: Petr Lautrbach <lautrbach@redhat.com>