libselinux: Fix audit2why.init error reporting
When a Python/C API raises an exception it should indicate it using
either NULL or -1 return value.

When /sys/fs/selinux was not mounted, audit2why.init() method failed,
used PyErr_SetString() but returned a value 1 instead of NULL.

See: https://docs.python.org/2/c-api/intro.html#exceptions

Fixes:
>>> import selinux.audit2why as audit2why
>>> audit2why.init()
-1
>>>
ValueError: You must specify the -p option with the path to the policy file.

Signed-off-by: Petr Lautrbach <plautrba@redhat.com>