sepolicy: don't use dnf.rpm.miscutils.splitFilename
It simply doesn't exist.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1309868

  $ sepolicy generate --init /usr/bin/rkt
  Traceback (most recent call last):
    File "/bin/sepolicy", line 650, in <module>
      args.func(args)
    File "/bin/sepolicy", line 519, in generate
      mypolicy.gen_writeable()
    File "/usr/lib64/python3.5/site-packages/sepolicy/generate.py", line 1309, in gen_writeable
      self.__extract_rpms()
    File "/usr/lib64/python3.5/site-packages/sepolicy/generate.py", line 1281, in __extract_rpms
      pkg_basename = dnf.rpm.miscutils.splitFilename(pkg.sourcerpm)[0]
  AttributeError: module 'dnf.rpm.miscutils' has no attribute 'splitFilename'

(cherry picked from commit b1964e0607f28e9c8d6f316497c7e6428e4d3393)