policycoreutils: Require at least one argument for 'semanage permissive -d'
Fixes: # semanage permissive -d
Traceback (most recent call last):
  File "/usr/sbin/semanage", line 860, in <module>
    do_parser()
  File "/usr/sbin/semanage", line 839, in do_parser
    args.func(args)
  File "/usr/sbin/semanage", line 654, in handlePermissive
    OBJECT.delete(args.type)
  File "/usr/lib/python3.4/site-packages/seobject/__init__.py", line 488, in delete
    for n in name.split():
AttributeError: 'NoneType' object has no attribute 'split'

Signed-off-by: Petr Lautrbach <plautrba@redhat.com>