Use universal_newlines option in subprocess.check_output() to override the default behaviour when subprocess.check_output() in audit.py returns bytes. With this change the output of subprocess.check_output() can be passed to split it per new lines.
Fixes:
Traceback (most recent call last):
  File "/bin/audit2allow", line 360, in <module>
    app.main()
  File "/bin/audit2allow", line 347, in main
    self.__process_input()
  File "/bin/audit2allow", line 175, in __process_input
    self.__avs = self.__parser.to_access()
  File "/usr/lib64/python3.4/site-packages/sepolgen/audit.py", line 584, in to_access
    avc.path = self.__restore_path(avc.name, avc.ino)
  File "/usr/lib64/python3.4/site-packages/sepolgen/audit.py", line 529, in __restore_path
    for file in output.split("\n"):
TypeError: 'str' does not support the buffer interface