mcstrans: Do not accept incomplete contexts
Fixes:
$ python3
> import selinux
> selinux.selinux_raw_context_to_color("xyz_u:xyz_r:xyz_t:")

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
OSError: [Errno 0] Error

:: [ 10:25:45 ] :: [  BEGIN   ] :: Running 'service mcstransd status'
Redirecting to /bin/systemctl status mcstransd.service
● mcstrans.service - Translates SELinux MCS/MLS labels to human readable form
   Loaded: loaded (/usr/lib/systemd/system/mcstrans.service; disabled; vendor preset: disabled)
   Active: failed (Result: core-dump) since Fri 2019-04-12 10:25:44 EDT; 1s ago
  Process: 16681 ExecStart=/sbin/mcstransd -f (code=dumped, signal=SEGV)
 Main PID: 16681 (code=dumped, signal=SEGV)

systemd[1]: mcstrans.service: Main process exited, code=dumped, status=11/SEGV
systemd[1]: mcstrans.service: Failed with result 'core-dump'.

Signed-off-by: Petr Lautrbach <plautrba@redhat.com>