policycoreutils: Improve Python 3 support for "sepolicy booleans"
fixes:
 # sepolicy booleans -a
Traceback (most recent call last):
  File "/usr/bin/sepolicy", line 647, in <module>
    args.func(args)
  File "/usr/bin/sepolicy", line 407, in booleans
    print("%s=_(\"%s\")" % (b, boolean_desc(b)))
  File "/usr/lib64/python3.4/site-packages/sepolicy/__init__.py", line 933, in boolean_desc
    desc = boolean.split("_")
TypeError: 'str' does not support the buffer interface

 # sepolicy booleans -b ftp_home_dir
Traceback (most recent call last):
  File "/usr/bin/sepolicy", line 647, in <module>
    args = parser.parse_args()
  File "/usr/lib64/python3.4/argparse.py", line 1728, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python3.4/argparse.py", line 1760, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.4/argparse.py", line 1948, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib64/python3.4/argparse.py", line 1925, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.4/argparse.py", line 1834, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.4/argparse.py", line 1129, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib64/python3.4/argparse.py", line 1760, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.4/argparse.py", line 1966, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib64/python3.4/argparse.py", line 1906, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python3.4/argparse.py", line 1834, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/bin/sepolicy", line 88, in __call__
    raise ValueError("%s must be an SELinux boolean:\nValid boolean: %s" % (v, ", ".join(booleans)))
TypeError: sequence item 0: expected str instance, bytes found