libsepol: remove unused attribute on a used argument
Since commit 58962eb3d847 ("libsepol,checkpolicy: add binary module
support for xperms") function avrule_read() has been using its "p"
argument even though it was previously marked unused. This makes clang
report:

    policydb.c:3276:7: error: 'p' was marked unused but was used
    [-Werror,-Wused-but-marked-unused].
        if (p->policyvers < MOD_POLICYDB_VERSION_XPERMS_IOCTL) {
            ^

Remove the attribute to make the code consistent again.

Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>

(cherry picked from SELinuxProject commit 8fe362f0121ab6d82f646ae51948a8df4a8834c6)